#!/usr/bin/env python3
"""assets/props/whiteboard.usd 의 `highlight` 스코프 생성기 — 활성 칸 **테두리 발광** (S6, 2026-09-16).

    python3 strawberry_harvest/scripts/scene_tools/gen_board_highlight.py            # 파일에 쓴다
    python3 strawberry_harvest/scripts/scene_tools/gen_board_highlight.py --check    # 쓰지 않고 요약만

일반 python3 에서 돈다 (표준 라이브러리만). whiteboard.usd 의 `def Scope "highlight"` 블록만
통째로 바꿔 쓰고, 나머지(board 메쉬·Looks·attach_points)는 손으로 관리하는 부분이라 건드리지 않는다.
프림 이름(nw·ne·sw·se, nw_nw … se_se)은 그대로다 — isaac_sim_viewport_display.py 가 이 이름으로
visibility 를 켜고 끄므로 HUD 코드는 바뀌지 않는다. 생성물은 씬 재로드 뒤 보인다.

09-10 살구색 면 채우기 → 09-16 시안 테두리 (영상 조언 1번)
  * 면을 채우면 익은 과실(빨강)과 살구색이 같은 난색이라 뭉개졌고, 화면에선 "보드가 통째로 물든" 것으로 읽혔다.
  * 이제 활성 칸의 **격자선 자리를 시안(#38BDF8) 발광 띠로 덮는다** — "격자 위에 덧씌운 강조".
    - 분면 띠 = 텍스처 격자선과 같은 두께 20mm (보드 폭 1090mm 의 1.8%; 조언 1.5~2%). 중심 십자는 경계 ±10mm,
      바깥 테두리는 가장자리 안쪽 0~20mm — 텍스처(1px = 1mm)의 검은 선이 정확히 그 자리라 선이 시안으로 바뀐 것처럼 보인다.
    - 세부 칸 띠 = 칸 안쪽 14mm. 텍스처에 세부 칸 선이 없으니 덮을 선도 없고, 한 단계 가는 띠가 "더 깊은 칸" 으로 읽힌다.
  * 보드 스케일이 (1.09, 0.79) 로 비균일이라 로컬 두께를 축마다 다르게 준다 — 화면에서는 두 축 다 같은 mm.
  * 이미시브는 낮게 시작(번짐 방지). 색·세기는 아래 상수 — 바꾸면 이 스크립트를 다시 돌린다.

시각 전용: 콜라이더 없음(physics_layer 는 whiteboard/board 만 건드린다), 이름에 strawberry 가 없어 fake_vision 도
발행하지 않는다. 플래너 입출력과 무관 (SUBMISSION_PLAN §2 게이트).
"""
import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DEF_USD = os.path.join(REPO, "strawberry_harvest/assets/props/whiteboard.usd")

# ---- 파라미터 ---------------------------------------------------------------------------
BOARD_SCALE = (1.09, 0.79)   # scenes/lab_environment.usd whiteboard xformOp:scale — 로컬 1×1 → 1090×790mm
GRID_LINE_MM = 20.0          # textures/paper_grid_custom_bg.png 격자선 두께 (1px = 1mm; 테두리·중심 십자만 있다)
QUAD_BORDER_MM = 20.0        # 분면 띠 두께 = 격자선과 같게
QUAD_OUTSET_MM = 10.0        # 분면 띠가 안쪽 경계(중심 십자) 를 넘어가는 양 = 격자선 반폭 → 선을 정확히 덮는다
SUB_BORDER_MM = 14.0         # 세부 칸 띠 두께 (칸 안쪽)
Z_QUAD, Z_SUB = -0.002, -0.0025   # 보드면 앞(로봇 쪽). 세부 칸이 분면 띠보다 조금 더 앞 — 겹칠 때 세부 칸이 이긴다
GLOW_SRGB = 0x38BDF8         # 조언: 시안 계열
EMISSIVE_INTENSITY = 4.0     # OmniPBR emissive_intensity. 기본(40) 은 번진다 — 낮게 시작

MARKER = "    # ---- highlight: generated by scripts/scene_tools/gen_board_highlight.py -- do not hand-edit ----"
OLD_START = "    # [2026-09-10] 분면 하이라이트 오버레이"       # 첫 실행 때 손으로 쓴 블록의 시작
END = '    def Scope "attach_points"'

QUADS = ("nw", "ne", "sw", "se")


def srgb_to_linear(hexv):
    out = []
    for shift in (16, 8, 0):
        c = ((hexv >> shift) & 255) / 255.0
        out.append(c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4)
    return tuple(out)


def mm(v, axis):
    """mm → 보드 로컬 단위 (축별 스케일 보정)."""
    return v / 1000.0 / BOARD_SCALE[axis]


def sub_bounds(x0, x1, y0, y1, s):
    """부모 [x0,x1]×[y0,y1] 안의 세부 칸 s. 이름 규칙은 분면과 같다 (nw = x 작은 쪽, y 작은 쪽)."""
    xm, ym = (x0 + x1) / 2.0, (y0 + y1) / 2.0
    return {"nw": (x0, xm, y0, ym), "ne": (xm, x1, y0, ym),
            "sw": (x0, xm, ym, y1), "se": (xm, x1, ym, y1)}[s]


def ring(x0, x1, y0, y1, tx, ty, z, ox=0.0, oy=0.0):
    """사각 띠 메쉬 — 바깥 4점 + 안쪽 4점, 면 4개 (아래·오른쪽·위·왼쪽). 보드 [-0.5, 0.5] 로 자른다."""
    X0, X1 = max(-0.5, x0 - ox), min(0.5, x1 + ox)
    Y0, Y1 = max(-0.5, y0 - oy), min(0.5, y1 + oy)
    ix0, ix1, iy0, iy1 = X0 + tx, X1 - tx, Y0 + ty, Y1 - ty
    assert ix0 < ix1 and iy0 < iy1, "띠가 칸보다 두껍다"
    pts = [(X0, Y0), (X1, Y0), (X1, Y1), (X0, Y1), (ix0, iy0), (ix1, iy0), (ix1, iy1), (ix0, iy1)]
    faces = [(0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]      # 반시계 (법선 +z, 기존 판과 같은 관례)
    return pts, faces, (X0, Y0, X1, Y1), z


def fmt(v):
    return ("%.6f" % v).rstrip("0").rstrip(".") if abs(v) >= 1e-9 else "0"


def mesh_usda(name, pts, faces, ext, z, comment=None):
    X0, Y0, X1, Y1 = ext
    p = ", ".join("(%s, %s, %s)" % (fmt(x), fmt(y), fmt(z)) for x, y in pts)
    idx = ", ".join(str(i) for f in faces for i in f)
    nrm = ", ".join(["(0, 0, 1)"] * (4 * len(faces)))
    head = ("        # %s\n" % comment) if comment else ""
    return head + '''        def Mesh "%(name)s" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {
            float3[] extent = [(%(x0)s, %(y0)s, %(z)s), (%(x1)s, %(y1)s, %(z)s)]
            int[] faceVertexCounts = [4, 4, 4, 4]
            int[] faceVertexIndices = [%(idx)s]
            rel material:binding = </whiteboard/highlight/Glow_Mat>
            normal3f[] normals = [%(nrm)s] (
                interpolation = "faceVarying"
            )
            point3f[] points = [%(pts)s]
            uniform token subdivisionScheme = "none"
            token visibility = "invisible"
        }
''' % dict(name=name, x0=fmt(X0), y0=fmt(Y0), x1=fmt(X1), y1=fmt(Y1), z=fmt(z), idx=idx, nrm=nrm, pts=p)


def material_usda():
    r, g, b = srgb_to_linear(GLOW_SRGB)
    return '''        # 발광 띠 머티리얼. 색은 sRGB #%(hex)06X → linear (OmniPBR 색 입력은 전부 linear).
        # 세기는 낮게 — 번지면(블룸) 격자선 위에 앉은 느낌이 사라진다. 조절은 생성 스크립트의 EMISSIVE_INTENSITY.
        def Material "Glow_Mat"
        {
            token outputs:mdl:displacement.connect = </whiteboard/highlight/Glow_Mat/Shader.outputs:out>
            token outputs:mdl:surface.connect = </whiteboard/highlight/Glow_Mat/Shader.outputs:out>
            token outputs:mdl:volume.connect = </whiteboard/highlight/Glow_Mat/Shader.outputs:out>

            def Shader "Shader"
            {
                uniform token info:implementationSource = "sourceAsset"
                uniform asset info:mdl:sourceAsset = @OmniPBR.mdl@
                uniform token info:mdl:sourceAsset:subIdentifier = "OmniPBR"
                color3f inputs:diffuse_color_constant = (%(r)s, %(g)s, %(b)s)
                bool inputs:enable_emission = 1
                color3f inputs:emissive_color = (%(r)s, %(g)s, %(b)s)
                float inputs:emissive_intensity = %(ei)s
                float inputs:reflection_roughness_constant = 1
                float inputs:specular_level = 0
                token outputs:out (
                    renderType = "material"
                )
            }
        }

''' % dict(hex=GLOW_SRGB, r=fmt(r), g=fmt(g), b=fmt(b), ei=fmt(EMISSIVE_INTENSITY))


def build_scope():
    tq = (mm(QUAD_BORDER_MM, 0), mm(QUAD_BORDER_MM, 1))
    oq = (mm(QUAD_OUTSET_MM, 0), mm(QUAD_OUTSET_MM, 1))
    ts = (mm(SUB_BORDER_MM, 0), mm(SUB_BORDER_MM, 1))
    bounds = {"nw": (-0.5, 0.0, -0.5, 0.0), "ne": (0.0, 0.5, -0.5, 0.0),
              "sw": (-0.5, 0.0, 0.0, 0.5), "se": (0.0, 0.5, 0.0, 0.5)}
    out = [MARKER + "\n", '''    # 활성 칸 테두리 발광 — 로봇이 작업 중인 / 가려는 영역 표시. 이 블록은 생성물이다:
    #   python3 strawberry_harvest/scripts/scene_tools/gen_board_highlight.py   (두께·색·세기·근거는 그 파일)
    # 분면 4장 + 세부 칸 16장, 전부 기본 invisible — isaac_sim_viewport_display.py 가 세션 레이어에서
    # visibility 를 켠다 (홈 = 분면 4장, 분면 = 그 한 장, 세부 자세 = 세부 칸 한 장).
    # 분면 이름은 로봇(world -Y 쪽)에서 보드를 본 방향: north = 로컬 -y, west = 로컬 -x
    #   (lab_environment.usd 의 orient Rx(-90°) 기준). nw: x<0,y<0  ne: x>0,y<0  sw: x<0,y>0  se: x>0,y>0
    # 분면 띠 %(q).0fmm (= 격자선, 중심 십자는 경계 ±%(o).0fmm 로 선을 덮는다), 세부 칸 띠 %(s).0fmm 안쪽.
    # 로컬 두께: x %(tx).6f / y %(ty).6f (보드 스케일 1.09 / 0.79 보정).
    def Scope "highlight"
    {
''' % dict(q=QUAD_BORDER_MM, o=QUAD_OUTSET_MM, s=SUB_BORDER_MM, tx=tq[0], ty=tq[1]), material_usda()]
    summary = []
    for q in QUADS:
        x0, x1, y0, y1 = bounds[q]
        pts, faces, ext, z = ring(x0, x1, y0, y1, tq[0], tq[1], Z_QUAD, oq[0], oq[1])
        out.append(mesh_usda(q, pts, faces, ext, z))
        summary.append((q, ext))
    out.append("        # 세부 칸 16장 — 분면을 2×2 로 나눈 것 (이름 = <분면>_<세부 칸>, scan_executor._subcell_of_pose 와 같은 사분 규칙)\n")
    for q in QUADS:
        for s in QUADS:
            x0, x1, y0, y1 = sub_bounds(*bounds[q], s)
            pts, faces, ext, z = ring(x0, x1, y0, y1, ts[0], ts[1], Z_SUB)
            out.append(mesh_usda("%s_%s" % (q, s), pts, faces, ext, z))
            summary.append(("%s_%s" % (q, s), ext))
    out.append("    }\n\n")
    return "".join(out), summary


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("usd", nargs="?", default=DEF_USD)
    ap.add_argument("--check", action="store_true", help="파일을 쓰지 않고 요약만")
    a = ap.parse_args()
    text = open(a.usd, encoding="utf-8").read()
    start = text.find(MARKER)
    if start < 0:
        start = text.find(OLD_START)
    end = text.find(END)
    if start < 0 or end < 0 or end < start:
        sys.exit("highlight 블록 경계를 못 찾았다 (%s / %s)" % (MARKER[:30], END))
    block, summary = build_scope()
    r, g, b = srgb_to_linear(GLOW_SRGB)
    print("glow #%06X -> linear (%.4f, %.4f, %.4f), emissive %.1f" % (GLOW_SRGB, r, g, b, EMISSIVE_INTENSITY))
    print("띠 두께 로컬 x/y: 분면 %.6f/%.6f  세부 %.6f/%.6f" % (mm(QUAD_BORDER_MM, 0), mm(QUAD_BORDER_MM, 1),
                                                        mm(SUB_BORDER_MM, 0), mm(SUB_BORDER_MM, 1)))
    for name, (X0, Y0, X1, Y1) in summary:
        print("  %-6s outer x[%+.4f, %+.4f] y[%+.4f, %+.4f]" % (name, X0, X1, Y0, Y1))
    if a.check:
        print("(--check: 쓰지 않음)")
        return
    new = text[:start] + block + text[end:]
    open(a.usd, "w", encoding="utf-8").write(new)
    print("wrote %s (%d -> %d lines)" % (a.usd, text.count("\n"), new.count("\n")))


if __name__ == "__main__":
    main()
